# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_covariance <- function(X) {
    .Call('_covarianceSelection_compute_covariance', PACKAGE = 'covarianceSelection', X)
}

