# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.c_compute_sigma <- function(X) {
    .Call('_covarianceSelection_c_compute_sigma', PACKAGE = 'covarianceSelection', X)
}

.c_compute_variance <- function(X, cov_mat) {
    .Call('_covarianceSelection_c_compute_variance', PACKAGE = 'covarianceSelection', X, cov_mat)
}

.c_compute_bootSigma <- function(X, noise_vec, cov_mat) {
    .Call('_covarianceSelection_c_compute_bootSigma', PACKAGE = 'covarianceSelection', X, noise_vec, cov_mat)
}

