# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_quantile <- function(X, quantile = 1) {
    .Call('_covarianceSelectionTmp_c_quantile', PACKAGE = 'covarianceSelectionTmp', X, quantile)
}

c_combn <- function(n) {
    .Call('_covarianceSelectionTmp_c_combn', PACKAGE = 'covarianceSelectionTmp', n)
}

c_armadillo <- function() {
    invisible(.Call('_covarianceSelectionTmp_c_armadillo', PACKAGE = 'covarianceSelectionTmp'))
}

c_compute_sigma <- function(X) {
    .Call('_covarianceSelectionTmp_c_compute_sigma', PACKAGE = 'covarianceSelectionTmp', X)
}

c_compute_variance <- function(X, cov_mat) {
    .Call('_covarianceSelectionTmp_c_compute_variance', PACKAGE = 'covarianceSelectionTmp', X, cov_mat)
}

c_compute_bootSigma <- function(X, noise_vec, cov_mat) {
    .Call('_covarianceSelectionTmp_c_compute_bootSigma', PACKAGE = 'covarianceSelectionTmp', X, noise_vec, cov_mat)
}

c_compute_covStat <- function(num_x, num_y, denom_x, denom_y, quantile = 1, squared = TRUE) {
    .Call('_covarianceSelectionTmp_c_compute_covStat', PACKAGE = 'covarianceSelectionTmp', num_x, num_y, denom_x, denom_y, quantile, squared)
}

c_compute_all_denom <- function(dat_list, cov_list) {
    .Call('_covarianceSelectionTmp_c_compute_all_denom', PACKAGE = 'covarianceSelectionTmp', dat_list, cov_list)
}

c_compute_all_test_stat <- function(num_list, denom_list, combn_mat, squared = TRUE) {
    .Call('_covarianceSelectionTmp_c_compute_all_test_stat', PACKAGE = 'covarianceSelectionTmp', num_list, denom_list, combn_mat, squared)
}

c_compute_all_numerator_bootstrap <- function(dat_list, noise_list, cov_list, remaining_idx) {
    .Call('_covarianceSelectionTmp_c_compute_all_numerator_bootstrap', PACKAGE = 'covarianceSelectionTmp', dat_list, noise_list, cov_list, remaining_idx)
}

